; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_06DGAFLEAA@?4pdata?$AA@			; `string'
PUBLIC	??_7ZDll@NT@@6B@				; NT::ZDll::`vftable'
EXTRN	__imp_strcmp:PROC
EXTRN	__imp_VirtualFree:PROC
EXTRN	__imp_VirtualAlloc:PROC
EXTRN	__imp_ZwFreeVirtualMemory:PROC
;	COMDAT ??_7ZDll@NT@@6B@
CONST	SEGMENT
??_7ZDll@NT@@6B@ DQ FLAT:??_EZDll@NT@@UEAAPEAXI@Z	; NT::ZDll::`vftable'
	DQ	FLAT:?QueryInterface@ZObject@NT@@UEAAJAEBU_GUID@@PEAPEAX@Z
CONST	ENDS
;	COMDAT ??_C@_06DGAFLEAA@?4pdata?$AA@
CONST	SEGMENT
??_C@_06DGAFLEAA@?4pdata?$AA@ DB '.pdata', 00H		; `string'
CONST	ENDS
PUBLIC	??1ZDll@NT@@UEAA@XZ				; NT::ZDll::~ZDll
PUBLIC	??_GZDll@NT@@UEAAPEAXI@Z			; NT::ZDll::`scalar deleting destructor'
PUBLIC	?QueryInterface@ZObject@NT@@UEAAJAEBU_GUID@@PEAPEAX@Z ; NT::ZObject::QueryInterface
EXTRN	??_EZDll@NT@@UEAAPEAXI@Z:PROC			; NT::ZDll::`vector deleting destructor'
pdata	SEGMENT
$pdata$??1ZDll@NT@@UEAA@XZ DD imagerel $LN8
	DD	imagerel $LN8+238
	DD	imagerel $unwind$??1ZDll@NT@@UEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_GZDll@NT@@UEAAPEAXI@Z DD imagerel $LN4
	DD	imagerel $LN4+54
	DD	imagerel $unwind$??_GZDll@NT@@UEAAPEAXI@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_GZDll@NT@@UEAAPEAXI@Z DD 010d01H
	DD	0420dH
xdata	ENDS
xdata	SEGMENT
$unwind$??1ZDll@NT@@UEAA@XZ DD 010901H
	DD	08209H
; Function compile flags: /Odtp
; File d:\zzz\winz\object.h
;	COMDAT ?QueryInterface@ZObject@NT@@UEAAJAEBU_GUID@@PEAPEAX@Z
_TEXT	SEGMENT
this$ = 8
__formal$ = 16
ppvObject$ = 24
?QueryInterface@ZObject@NT@@UEAAJAEBU_GUID@@PEAPEAX@Z PROC ; NT::ZObject::QueryInterface, COMDAT

; 25   : 	{

	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx

; 26   : 		*ppvObject = 0;

	mov	rax, QWORD PTR ppvObject$[rsp]
	mov	QWORD PTR [rax], 0

; 27   : 		return E_NOINTERFACE;

	mov	eax, -2147467262			; ffffffff80004002H

; 28   : 	}

	ret	0
?QueryInterface@ZObject@NT@@UEAAJAEBU_GUID@@PEAPEAX@Z ENDP ; NT::ZObject::QueryInterface
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??_GZDll@NT@@UEAAPEAXI@Z
_TEXT	SEGMENT
this$ = 48
__flags$ = 56
??_GZDll@NT@@UEAAPEAXI@Z PROC				; NT::ZDll::`scalar deleting destructor', COMDAT
$LN4:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	rcx, QWORD PTR this$[rsp]
	call	??1ZDll@NT@@UEAA@XZ			; NT::ZDll::~ZDll
	mov	eax, DWORD PTR __flags$[rsp]
	and	eax, 1
	test	eax, eax
	je	SHORT $LN1@scalar
	mov	rcx, QWORD PTR this$[rsp]
	call	??3@YAXPEAX@Z				; operator delete
$LN1@scalar:
	mov	rax, QWORD PTR this$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??_GZDll@NT@@UEAAPEAXI@Z ENDP				; NT::ZDll::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Odtp
; File d:\zzz\dbgnew\dll.cpp
_TEXT	SEGMENT
RegionSize$ = 32
tv131 = 40
$T1 = 48
this$ = 80
??1ZDll@NT@@UEAA@XZ PROC				; NT::ZDll::~ZDll

; 30   : {

$LN8:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H
	mov	rax, QWORD PTR this$[rsp]
	lea	rcx, OFFSET FLAT:??_7ZDll@NT@@6B@
	mov	QWORD PTR [rax], rcx

; 31   : 	SIZE_T RegionSize;
; 32   : #ifdef _WIN64
; 33   : 	if (_RtfPresent)

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+92]
	shr	eax, 3
	and	eax, 1
	test	eax, eax
	je	SHORT $LN3@ZDll

; 34   : 	{
; 35   : 		ZwFreeVirtualMemory(NtCurrentProcess(), (void**)&_prtf, &(RegionSize = 0), MEM_RELEASE);

	mov	QWORD PTR RegionSize$[rsp], 0
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 64					; 00000040H
	mov	r9d, 32768				; 00008000H
	lea	r8, QWORD PTR RegionSize$[rsp]
	mov	rdx, rax
	mov	rcx, -1
	call	QWORD PTR __imp_ZwFreeVirtualMemory
$LN3@ZDll:

; 36   : 	}
; 37   : #endif
; 38   : 
; 39   : 	if (_Buffer)

	mov	rax, QWORD PTR this$[rsp]
	cmp	QWORD PTR [rax+56], 0
	je	SHORT $LN2@ZDll

; 40   : 	{
; 41   : 		ZwFreeVirtualMemory(NtCurrentProcess(), &_Buffer, &(RegionSize = 0), MEM_RELEASE);

	mov	QWORD PTR RegionSize$[rsp], 0
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 56					; 00000038H
	mov	r9d, 32768				; 00008000H
	lea	r8, QWORD PTR RegionSize$[rsp]
	mov	rdx, rax
	mov	rcx, -1
	call	QWORD PTR __imp_ZwFreeVirtualMemory
$LN2@ZDll:

; 42   : 	}
; 43   : 
; 44   : 	if (_ImageName)

	mov	rax, QWORD PTR this$[rsp]
	cmp	QWORD PTR [rax+48], 0
	je	SHORT $LN1@ZDll

; 45   : 	{
; 46   : 		delete _ImageName;

	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax+48]
	mov	QWORD PTR $T1[rsp], rax
	mov	rcx, QWORD PTR $T1[rsp]
	call	??3@YAXPEAX@Z				; operator delete
$LN1@ZDll:

; 47   : 	}
; 48   : 
; 49   : 	RemoveEntryList(this);

	cmp	QWORD PTR this$[rsp], 0
	je	SHORT $LN6@ZDll
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 16
	mov	QWORD PTR tv131[rsp], rax
	jmp	SHORT $LN7@ZDll
$LN6@ZDll:
	mov	QWORD PTR tv131[rsp], 0
$LN7@ZDll:
	mov	rcx, QWORD PTR tv131[rsp]
	call	RemoveEntryList

; 50   : }

	mov	rcx, QWORD PTR this$[rsp]
	call	??1ZObject@NT@@MEAA@XZ			; NT::ZObject::~ZObject
	add	rsp, 72					; 00000048H
	ret	0
??1ZDll@NT@@UEAA@XZ ENDP				; NT::ZDll::~ZDll
_TEXT	ENDS
xdata	ENDS
END
